import cities from './cities.json' with { type: 'json' }
import { SearchIndex } from './search-index.js'
// import { entries, set } from './idb-keyval.js'

/* global self, clients */

const { PUT, DOCUMENT_COUNT } = new SearchIndex()
// , DICTIONARY, DOCUMENT_COUNT later on

/* ### ################################################################# ### */
/* ### BroadcastChannel init + event listener                            ### */

// const broadcastChannel = new BroadcastChannel('workerserver_app')

/* ### ################################################################# ### */
/* ### Sets the service worker in controll of all clients                ### */

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim())
})

/* ### ################################################################# ### */
/* ### Fetch event listener + control switch                             ### */

// ### Url parts extraction                                              ### */
const regexUrl = function (url) {
  const urlParts = {
    query: null,
    json: null
  }

  urlParts.query = (/(?<=\/API\?).*(?=={)/.exec(url))[0]
  urlParts.json = (/{.*}$/.exec(url))[0]

  if (urlParts.json !== 'object') {
    urlParts.json = JSON.parse(urlParts.json)
  }

  return urlParts
}

/* ### ################################################################# ### */
/* ### search-index functions                                            ### */

async function putJson (json) {
  const result = await PUT(json)
  console.log('### ###JSON: ' + JSON.stringify(json))
  return result
}

async function documentCount () {
  const totalDocs = await DOCUMENT_COUNT()
  return totalDocs
}

// howto typeahead: https://github.com/fergiemcdowall/search-index/blob/master/docs/FAQ.md#how-do-i-make-a-simple-typeahead--autosuggest--matcher
// howto async/await: https://stackoverflow.com/questions/49938266/how-to-return-values-from-async-functions-using-async-await-from-function


// ### fetch() event listener                                            ### */
self.addEventListener('fetch', function (event) {
  let responseJson
  if (decodeURI(event.request.url).includes('API')) {
    const urlParts = regexUrl(decodeURI(event.request.url))
    console.log(JSON.stringify(urlParts))
    switch (urlParts.query) {
      case 'PUT':
        (async () => {
          const result = await putJson(cities)
          console.log(result)
        })()
        responseJson = { response: 'Started putting data' } // search-index PUT-stuff
        break
      case 'DOCUMENT_COUNT':
        (async () => {
          const docs = await documentCount()
          console.log(docs)
        })()
        responseJson = { response: 'Some data indexed?' } // search-index DOCUMET_COUNT-stuff
        break
      default:
        // error-message into an object and returing it. To make an error-chekc in the frontend
        console.log('### Servide Worker error')
        responseJson = { type: 'error', message: 'Error: Not a known query-part in the URL' }
    }

    // ### Response back to app.js                                       ### */
    event.respondWith(
      (async () => {
        const responseOptions = {
          headers: { 'Content-Type': 'application/json' },
          status: 200,
          statusText: 'Ok - Response file generated by webpage-server.js'
        }
        // Just returning a JSON object without hitting the server
        return new Response(JSON.stringify(responseJson), responseOptions)
      })()
    )
  }
})
