import { add, subtract, multiply, divide } from './math-lib.js'
// import { entries, set } from './idb-keyval.js'

/* global self, clients */

/* ### ################################################################# ### */
/* ### BroadcastChannel init + event listener                            ### */

// const broadcastChannel = new BroadcastChannel('workerserver_app')

/* ### ################################################################# ### */
/* ### Sets the service worker in controll of all clients                ### */

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim())
})

/* ### ################################################################# ### */
/* ### Fetch event listener + control switch                             ### */

// ### Url parts extraction                                              ### */
const regexUrl = function (url) {
  console.log('### ### url: ' + url)
  const urlParts = {
    query: null,
    json: null
  }

  urlParts.query = (/(?<=\/API\?).*(?=={)/.exec(url))[0]
  urlParts.json = (/{.*}$/.exec(url))[0]

  // console.log('### ### query: ' + urlParts.query + '\n### ### json: ' + urlParts.json)

  if (urlParts.json !== 'object') {
    urlParts.json = JSON.parse(urlParts.json)
  }

  return urlParts
}

// ### fetch() event listener                                            ### */
self.addEventListener('fetch', function (event) {
  let responseJson
  if (decodeURI(event.request.url).includes('API')) {
    // ### for each math function call a history function that:
    // ### A: Generates a UUID
    // ### B: sets the new math to idb-keyval
    // ### C: get all entries
    // ### D: postMessage to all clients
    // const uuid = self.crypto.randomUUID()
    const urlParts = regexUrl(decodeURI(event.request.url))
    switch (urlParts.query) {
      case 'add':
        responseJson = add(urlParts.json.num1, urlParts.json.num2)
        break
      case 'subtract':
        responseJson = subtract(urlParts.json.num1, urlParts.json.num2)
        break
      case 'multiply':
        responseJson = multiply(urlParts.json.num1, urlParts.json.num2)
        break
      case 'divide':
        responseJson = divide(urlParts.json.num1, urlParts.json.num2)
        break
      default:
        // error-message into an object and returing it. To make an error-chekc in the frontend
        console.log('### Servide Worker error')
        responseJson = { type: 'error', message: 'Error: Not a known query-part in the URL' }
    }

    // ### Response back to app.js                                       ### */
    event.respondWith(
      (async () => {
        const responseOptions = {
          headers: { 'Content-Type': 'application/json' },
          status: 200,
          statusText: 'Ok - Response file generated by webpage-server.js'
        }
        // Just returning a JSON object without hitting the server
        return new Response(JSON.stringify(responseJson), responseOptions)
      })()
    )
  }
})
